# Generated by Django 5.1.3 on 2024-12-24 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.AddField(
            model_name='promotion',
            name='quantity_limit',
            field=models.IntegerField(default=-1, verbose_name='Giới hạn số lượng (-1 là không giới hạn)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Phần trăm giảm giá (%)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(upload_to='promotion/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Còn hiệu lực'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên mã khuyến mãi'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
    ]
