# Generated by Django 5.1.3 on 2024-12-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_promotion_quantity_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hóa đơn')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('sumary', models.TextField(verbose_name='Thông tin')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='limit',
            field=models.IntegerField(default=-1, verbose_name='Số lượng giới hạn (-1 nếu không giới hạn)'),
        ),
    ]
