# Generated by Django 5.1.3 on 2024-12-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bill_promotion_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='limit',
            new_name='limit_count',
        ),
    ]
