# Generated by Django 5.1.3 on 2024-12-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_limit_promotion_limit_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotion',
            old_name='limit_count',
            new_name='limit',
        ),
    ]
