# Generated by Django 5.1.3 on 2024-12-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_limit_count_promotion_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên dịch vụ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá dịch vụ (VNĐ)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Hóa đơn', 'verbose_name_plural': 'Các hóa đơn'},
        ),
    ]
